### ISSUE TITLE
I'm trying to use the addon with storybook and react, but can't build storybook once I installed the addon

### ISSUE THREAD

**Issue by Kettss1** [RyanClementsHax/storybook-addon-next#111]
### Describe the bug

I had a React project and tried to use the addon-next to work properly with Sass, since in my researches it helps with some problems that i was facing when using just the Storybook default config for Sass. But, when I installed sddon-next and tried to build my project, I got an error.

### Your minimal, reproducible example

Default config from docs

### Steps to reproduce

1. Just reproduce the steps on the docs. yarn add --dev storybook-addon-next, added 'storybook-addon-next' to my 'main.js' and then yarn build-storybook

### Expected behavior

I expected to build storybook correctly

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/89028159/181069843-7d4c6cef-2a2a-4075-bee1-bc5d96f49f12.png)
![image](https://user-images.githubusercontent.com/89028159/181069892-1a70a8f0-bcad-429d-87a5-f01ff30a6789.png)

### Platform

- OS: Ubuntu

### storybook-addon-next version

1.6.7

**Comment by RyanClementsHax** [comment]
Thanks for opening the issue!

I believe you are seeing this conflict as a result of including the CRA preset. Try removing that.

**Comment by Kettss1** [comment]
I did it, but still having this issue. Also, I had another error, probably a result from removing CRA from main.js

![image](https://user-images.githubusercontent.com/89028159/181081607-618ff765-6fab-47e5-89b6-0244f1d25f52.png)

**Comment by MONTYYYYY** [comment]
Any solution for this yet?

**Comment by Kettss1** [comment]
not yet. still waiting

**Comment by RyanClementsHax** [comment]
Thanks for you patience. I was not able to reproduce your error. Are you able to provide a reproduction repo I can take a look at?
