### ISSUE TITLE
Autoprefixer not working

### ISSUE THREAD

**Issue by ChazUK** [RyanClementsHax/storybook-addon-next#112]
### Describe the bug

I'm trying to use CSS modules with SCSS and have come up against an issue where the autoprefixer is not working on storybook, but working correctly when I run NextJS.

The `mask-image` property is not being prefixed to support Chrome and the webkit browsers.

<img width="153" alt="Screenshot 2022-08-03 at 15 14 13" src="https://user-images.githubusercontent.com/768108/182630737-3d6d8d0e-2e10-41cb-9fb5-b134b8fefd83.png">

### Your minimal, reproducible example

https://stackblitz.com/edit/nextjs-a7vvxx

### Steps to reproduce

.storybook/main.js
```
module.exports = {
  stories: [
    "../components/**/*.stories.mdx",
    "../components/**/*.stories.@(js|jsx|ts|tsx)",
  ],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions",
    "storybook-addon-next",
  ],
  framework: "@storybook/react",
  core: {
    builder: "@storybook/builder-webpack5",
  },
  staticDirs: ["../public"],
};
```

.browserlistrc
```
defaults
last 2 versions
not IE 11
```

scss
```
.playing {
  width: 50px;
  height: 50px;
  background: #FFFFFF;
  mask-image: url(https://upload.wikimedia.org/wikipedia/commons/0/03/Font_Awesome_5_solid_play-circle.svg);
  mask-mode: alpha;
}
```

deps
```
"dependencies": {
    "@mantine/core": "^4.2.12",
    "@mantine/hooks": "^4.2.12",
    "@mantine/next": "^4.2.12",
    "classnames": "^2.3.1",
    "date-fns": "^2.29.1",
    "framer-motion": "^6.5.1",
    "next": "12.2.2",
    "react": "18.2.0",
    "react-dom": "18.2.0"
  },
  "devDependencies": {
    "@babel/core": "^7.18.9",
    "@storybook/addon-actions": "^6.5.9",
    "@storybook/addon-essentials": "^6.5.9",
    "@storybook/addon-interactions": "^6.5.9",
    "@storybook/addon-links": "^6.5.9",
    "@storybook/addon-postcss": "^3.0.0-alpha.1",
    "@storybook/builder-webpack5": "^6.5.9",
    "@storybook/manager-webpack5": "^6.5.9",
    "@storybook/react": "^6.5.9",
    "@storybook/testing-library": "^0.0.13",
    "@types/node": "18.0.6",
    "@types/react": "18.0.15",
    "@types/react-dom": "18.0.6",
    "babel-loader": "^8.2.5",
    "eslint": "8.20.0",
    "eslint-config-next": "12.2.2",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-storybook": "^0.6.1",
    "postcss": "^8.4.14",
    "sass": "^1.54.0",
    "storybook-addon-next": "^1.6.7",
    "stylelint": "^14.9.1",
    "stylelint-config-idiomatic-order": "^8.1.0",
    "stylelint-config-prettier-scss": "^0.0.1",
    "stylelint-config-standard-scss": "^5.0.0",
    "typescript": "4.7.4",
    "typescript-plugin-css-modules": "^3.4.0"
  }
```

### Expected behavior

<img width="170" alt="Screenshot 2022-08-03 at 15 14 20" src="https://user-images.githubusercontent.com/768108/182630704-c9e1f03c-0074-4869-8a0b-964b1241062e.png">

### How often does this bug happen?

Every time

### Platform

macOS, Chrome

### storybook-addon-next version

1.6.7

### Additional context

none

**Comment by ChazUK** [comment]
😞

**Comment by a-tokyo** [comment]
facing this issue as well

**Comment by Eneko96** [comment]
Facing this issue as well

**Comment by RyanClementsHax** [comment]
Regarding the upcoming release of storybook v7 and the accompanying framework api that replaces this addon. I'm switching this package into "keep the lights on" mode and directing everyone using this addon to switch to storybook's framework api.

Please report any issues you have with migrating though :)
