### ISSUE TITLE
Incopatibility with @storybook/builder-vite

### ISSUE THREAD

**Issue by dvakatsiienko** [RyanClementsHax/storybook-addon-next#120]
### Describe the bug

Using **[storybook-addon-next](https://github.com/RyanClementsHax/storybook-addon-next)** in combination with **[builder-vite](https://github.com/storybookjs/builder-vite)** produces an error once storybook server started.

[Reproduce repo link](https://github.com/dvakatsiienko/next-vite-storybook).
I've added instruction to start.

**All packages have latest versions**.

**A warning message**:
```
Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: 
```

**Error message is somehow related with `next-image-stub.js`**:
```
Uncaught TypeError: Invalid Version: undefined
    at new SemVer (semver.js:19:13)
    at compare (compare.js:3:3)
    at Object.gt (gt.js:2:29)
    at node_modules/storybook-addon-next/dist/images/next-image-stub.js (next-image-stub.js:7:22)
    at __require2 (chunk-S5KM4IGW.js?v=7ad206d8:18:50)
    at node_modules/storybook-addon-next/dist/preview.js (preview.js:7:1)
    at __require2 (chunk-S5KM4IGW.js?v=7ad206d8:18:50)
    at dep:storybook-addon-next_dist_preview__js:1:16
```

### Your minimal, reproducible example

Branch **bug**:
https://github.com/dvakatsiienko/next-vite-storybook/tree/bug

### Steps to reproduce

1. Clone repository
2. yarn
3. yarn storybook:start
4. Once Vite bundled, go to `http://localhost:6006/`
5. Inspect an error in console

### Expected behavior

As a user I expect a correctly rendered page.

### How often does this bug happen?

Every time

### Screenshots or Videos

https://user-images.githubusercontent.com/15727958/192000483-00c4dd09-4123-46cc-8772-d5f12be5a7ba.mp4

### Platform

- OS MacOS
- All packages latest versions

### storybook-addon-next version

1.6.9

**Comment by RyanClementsHax** [comment]
Thanks for opening this.

As of right now this addon doesn't support the vite builder because nextjs doesn't use vite and it's a lot for just me to maintain just the webpack version :(

Until I can get more help with this package, I can't take on that work :( sorry
