### ISSUE TITLE
next 13 support

### ISSUE THREAD

**Issue by bonesoul** [RyanClementsHax/storybook-addon-next#123]
### Describe the bug

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: storybook-addon-next@1.6.9
npm ERR! Found: next@13.0.0
npm ERR! node_modules/next
npm ERR!   next@"13.0.0" from the root project
npm ERR!   peer next@"^8.1.1-canary.54 || >=9.0.0" from next-seo@5.8.0
npm ERR!   node_modules/next-seo
npm ERR!     next-seo@"5.8.0" from the root project
npm ERR!   1 more (next-sitemap)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer next@"^9.0.0 || ^10.0.0 || ^11.0.0 || ^12.0.0" from storybook-addon-next@1.6.9
npm ERR! node_modules/storybook-addon-next
npm ERR!   dev storybook-addon-next@"1.6.9" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: next@12.3.1
npm ERR! node_modules/next
npm ERR!   peer next@"^9.0.0 || ^10.0.0 || ^11.0.0 || ^12.0.0" from storybook-addon-next@1.6.9
npm ERR!   node_modules/storybook-addon-next
npm ERR!     dev storybook-addon-next@"1.6.9" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\shala\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\shala\AppData\Local\npm-cache\_logs\2022-10-25T22_25_34_802Z-debug-0.log
npm ERR! code 1
npm ERR! path E:\source\vizesizgezi
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c cd dataset && npm install && cd ../frontend && npm install && cd ../migrator && npm install && cd ../tasks && npm install && cd ../tools/image_gen && npm install && cd ../..

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\shala\AppData\Local\npm-cache\_logs\2022-10-25T22_25_21_001Z-debug-0.log
```

### Your minimal, reproducible example

n/a

### Steps to reproduce

upgrade next to 13.0.0.

### Expected behavior

should install properly

### How often does this bug happen?

Every time

### Platform

any

### storybook-addon-next version

1.6.9

**Comment by carneiroDotDev** [comment]
I simply deleted the `storybook-addon-next` from my `package.json`and all the images seem to be rendering fine. Notice there was an important change in how the `<Image />` component works and maybe that is why the package wasn't needed _on my side_ anymore (I am doing direct imports from next public folder).

**Comment by kasvith** [comment]
Yep please upgrade this to Next13

**Comment by pm0u** [comment]
I also ran into errors with this plugin. I opted to follow the guide from storybook [here](https://storybook.js.org/blog/get-started-with-storybook-and-next-js/) to force unoptimized images. I also ran into an issue with Next 13 that the `next/link` component would not render the child anchor when you pass a React element as the child (text nodes seem to work fine) - found a workaround here: https://github.com/storybookjs/storybook/issues/19813

**Comment by RyanClementsHax** [comment]
Thank you all for your patience :)

**Comment by bonesoul** [comment]
@RyanClementsHax 
package.json still lacks next-13 in peer dependencies:

https://github.com/RyanClementsHax/storybook-addon-next/blob/main/package.json#L83

**Comment by RyanClementsHax** [comment]
crap

**Comment by RyanClementsHax** [comment]
Try v1.7.1

I just pushed an update

**Comment by wfischer42** [comment]
@kodai3, I wasn't able to get this working using `next/legacy/image`, but it worked again after applying the [codemod](https://nextjs.org/docs/messages/next-image-upgrade-to-13).

**Comment by kodai3** [comment]
I know it works with codemode but style went wrong at some part. I just used mock while relpacing from legacy to new

```preview.js
import * as NextLegacyImage from 'next/legacy/image';

const OriginalNextImage = NextLegacyImage.default;

Object.defineProperty(NextLegacyImage, 'default', {
  configurable: true,
  value: (props) => <OriginalNextImage {...props} unoptimized loader={({ src }) => src} />,
});
```
