### ISSUE TITLE
Error: NextRouter was not mounted. https://nextjs.org/docs/messages/next-router-not-mounted

### ISSUE THREAD

**Issue by zigang93** [RyanClementsHax/storybook-addon-next#133]
### Describe the bug

I need to wrap my  custom `StoreProvider` provider in decorator 

```js
export const decorators = [
  (Story, context) => (
          <StoreProvider>
              <Story />
          </StoreProvider>
  ),
]

```

inside my `StoreProvider` (react context) got wrote `useRouter` hook from nextjs.. 
because of decorator is render outside from nextjs.. so how can I solve it?

I am using nextjs 13

### Your minimal, reproducible example

-

### Steps to reproduce

none, private project

### Expected behavior

expect next router to be mounted

### Platform

- OS: Macos

### storybook-addon-next version

v1.6.10

**Comment by RyanClementsHax** [comment]
Hello,
thanks for opening up the issue. Could you please provide a link to a reproduction repo so I could take a further look?

Btw this seems to be an issue with decorator ordering. I'm guessing the addon's decorators don't get applied before your custom decorators?

**Comment by wilsonbljr** [comment]
Hi, I had the same problem when using the decorators to insert the next-intl provider on my storybook. 

I solved by adding the RouterDecorator directly in the Decorators array

```js
// preview.js
import { RouterDecorator } from 'storybook-addon-next/dist/routing/decorator';

export const decorators = [
  (Story) => (
      <NextIntlProvider
        formats={formats}
        timeZone={process.env['TIME_ZONE']}
        locale="pt-BR"
        messages={messages}
        defaultTranslationValues={defaultTranslationValues}>
        <Story />
      </NextIntlProvider>
  ),
  RouterDecorator, // <-- This worked for my case
];
```

I'm using the storybook-addon-next v1.7.1
