### ISSUE TITLE
Importing font files (*.woff, *.ttf)

### ISSUE THREAD

**Issue by czebe** [RyanClementsHax/storybook-addon-next#15]
### Describe the bug

Loading fonts seems to be failing with:

```
ModuleBuildError: Module build failed (from ./node_modules/storybook-addon-next/dist/images/next-image-loader-stub.js):
TypeError: unsupported file type: undefined (file: undefined)
    at lookup (/Users/.../node_modules/image-size/dist/index.js:52:11)
    at imageSize (/Users/.../node_modules/image-size/dist/index.js:104:16)
```

Webpack config shows that the font is being loaded via `next-image-loader-stub`:

```
{
    test: /\.(svg|ico|jpg|jpeg|png|apng|gif|eot|otf|webp|ttf|woff|woff2|cur|ani|pdf)(\?.*)?$/,
        use: [
              {
                loader: '/Users/.../node_modules/storybook-addon-next/dist/images/next-image-loader-stub.js',
                options: { filename: 'static/media/[path][name][ext]' }
              }
        ]
  },
```

Perhaps it's because font files won't have a `width` and `height`?
https://github.com/RyanClementsHax/storybook-addon-next/blob/6583c2080386f72fdebc49ff93a2b8262d1219bc/src/images/next-image-loader-stub.ts#L24

Just guessing... Would love to hear your insights.
Thanks!

### Your minimal, reproducible example

http://forking.example.on.codesandbox.fails.to.build

### Steps to reproduce

1. add a font static asset
2. add css that imports font file
3. storybook start fails

### Expected behavior

I expected static file imports to work as before, but `next-image-loader-stub` seems to be breaking.

### Platform

- OS: MacOS X
- Node 16

### storybook-addon-next version

v1.3.1

**Comment by RyanClementsHax** [comment]
Oops! You're totally right. I naively overwrote the storybook rule for asset compilation not realizing it also included fonts! Thanks for bringing this up.

Side note, the reproduction repo link doesn't work. Are you able to provide a working link? I just want to make sure I fix your problem for sure.

**Comment by RyanClementsHax** [comment]
Upon further review, the [next-image-loader](https://github.com/vercel/next.js/blob/39d3210776d37e7dc11e77b54a65b33b5454c0ce/packages/next/build/webpack/loaders/next-image-loader.js) (the loader this addon in part mimics) is configured to only take [these file extensions](https://github.com/vercel/next.js/blob/canary/packages/next/build/webpack-config.ts#L210). `storybook-addon-next` should be updated accordingly to mimic what is happening in nextjs.

**Comment by czebe** [comment]
This is how storybook configures asset loaders. I’ll try to put together a minimal reproduction to exclude any other interference.

https://github.com/storybookjs/storybook/blob/e07fdc734f60e542f0f5f6339a31e34412113416/lib/builder-webpack5/src/preview/base-webpack.config.ts#L61

**Comment by czebe** [comment]
Here's a reproduction:

`yarn dev` vs `yarn storybook`

<img width="395" alt="Screenshot 2022-02-02 at 22 26 25" src="https://user-images.githubusercontent.com/2728671/152240454-9b2ced4b-9cff-4321-ac5e-5dfdacec7b9b.png">

<img width="997" alt="Screenshot 2022-02-02 at 22 34 41" src="https://user-images.githubusercontent.com/2728671/152241145-439fa38c-f4d3-4399-888a-cf7b26e1507d.png">

StackBlitz: https://stackblitz.com/edit/nextjs-bh4hfb?file=pages/index.tsx
Source: https://github.com/czebe/storybook-next-images-loader-repro

**Comment by andykenward** [comment]
Also running into a similar issue when using a custom svg webpack loader `@svgr/webpack`.

```
ModuleBuildError: Module build failed (from ./node_modules/storybook-addon-next/dist/images/next-image-loader-stub.js):
TypeError: unsupported file type: undefined (file: undefined)
```

Next.js has a check for custom svg webpack loaders [here](https://github.com/vercel/next.js/blob/b7725133f867b5e530dd4bb5d1fd8d5d389e3364/packages/next/build/webpack-config.ts#L1763-L1778)

**Comment by RyanClementsHax** [comment]
I was able to solve the issue with the pull request above. For anyone interested the TLDR is that after configuring the image loader for only the image types that the nextjs image loader takes, I needed to make sure that the `css-loader` was configured to handle imports and url's in css like nextjs does [here](https://github.com/vercel/next.js/blob/b7725133f867b5e530dd4bb5d1fd8d5d389e3364/packages/next/build/webpack/config/blocks/css/loaders/modules.ts#L33). Lastly, I had to make sure that the images required by css was outputted as an asset.

A fix will come soon. I'm just refactoring the examples to include this case.

**Comment by RyanClementsHax** [comment]
> Also running into a similar issue when using a custom svg webpack loader `@svgr/webpack`.
> 
> ```
> ModuleBuildError: Module build failed (from ./node_modules/storybook-addon-next/dist/images/next-image-loader-stub.js):
> TypeError: unsupported file type: undefined (file: undefined)
> ```
> 
> Next.js has a check for custom svg webpack loaders [here](https://github.com/vercel/next.js/blob/b7725133f867b5e530dd4bb5d1fd8d5d389e3364/packages/next/build/webpack-config.ts#L1763-L1778)

Would you mind opening an issue with your specific case and a reproduction repo? I'd love to help you out there.

**Comment by RyanClementsHax** [comment]
Also @czebe thanks for the reproduction repo. That was very helpful!

**Comment by czebe** [comment]
Thanks Ryan! Fantastic work!
I noticed a different, smaller issue as well. Will open another ticket when I get a chance.
