### ISSUE TITLE
Nextjs Image Error message Failed to parse src "static/media/public/logo.jpeg" on next/legacy/image on Nextv13

### ISSUE THREAD

**Issue by mAAdhaTTah** [RyanClementsHax/storybook-addon-next#188]
### Describe the bug

Similar issue as #122, except this is for Nextjsv13 with `next/legacy/image`. My hunch is this is because the stub doesn't touch the legacy image.

### Your minimal, reproducible example

Can add if needed.

### Steps to reproduce

1. Create a story using `next/legacy/image` + a static import.
2. Load it up in Storybook
3. See the error

### Expected behavior

Legacy image is mocked similar to default `next/image` component.

### How often does this bug happen?

Every time

### Platform

- OSX
- Nextjs v13
- Storybook v6

### storybook-addon-next version

v1.8.0

**Comment by RyanClementsHax** [comment]
You would be correct. This addon has been placed on Keep The Lights On mode as @storybook/nextjs is now the preferred solution.

If you would like some help migrating, see the migration docs on the README and let me know if you run into any issues :)
