### ISSUE TITLE
Does not work with yarn workspaces

### ISSUE THREAD

**Issue by volkyeth** [RyanClementsHax/storybook-addon-next#23]
### Describe the bug

When using in a project that is a [yarn workspace](https://classic.yarnpkg.com/lang/en/docs/workspaces/) (on a monorepo setup), the plugin fails to find modules because of node_modules being hoisted up to the root folder:

```
yarn storybook
yarn run v1.22.17
$ start-storybook -p 6006 -s public
info @storybook/react v6.4.18
info 
(node:61699) DeprecationWarning: --static-dir CLI flag is deprecated, see:

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated---static-dir-cli-flag
(Use `node --trace-deprecation ...` to show where the warning was created)
info => Loading presets
info => Serving static files from ./public at /
info => Using implicit CSS loaders
ERR! Error: Cannot find module '<project-root>/storybook-addon-next/examples/with-tailwindcss/node_modules/next/package.json'
ERR! Require stack:
ERR! - <project-root>/storybook-addon-next/examples/node_modules/storybook-addon-next/dist/utils.js
ERR! - <project-root>/storybook-addon-next/examples/node_modules/storybook-addon-next/dist/preset.js
ERR! - <project-root>/storybook-addon-next/examples/node_modules/@storybook/core-common/dist/cjs/presets.js
ERR! - <project-root>/storybook-addon-next/examples/node_modules/@storybook/core-common/dist/cjs/index.js
ERR! - <project-root>/storybook-addon-next/examples/node_modules/@storybook/core-server/dist/cjs/index.js
ERR! - <project-root>/storybook-addon-next/examples/node_modules/@storybook/core/dist/cjs/server.js
ERR! - <project-root>/storybook-addon-next/examples/node_modules/@storybook/core/server.js
ERR! - <project-root>/storybook-addon-next/examples/node_modules/@storybook/react/dist/cjs/server/index.js
ERR! - <project-root>/storybook-addon-next/examples/node_modules/@storybook/react/bin/index.js
ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!     at getNextjsVersion (<project-root>/storybook-addon-next/examples/node_modules/storybook-addon-next/dist/utils.js:9:1)
ERR!     at configureStaticImageImport (<project-root>/storybook-addon-next/examples/node_modules/storybook-addon-next/dist/images/webpack.js:14:50)
ERR!     at configureImages (<project-root>/storybook-addon-next/examples/node_modules/storybook-addon-next/dist/images/webpack.js:8:5)
ERR!     at <project-root>/storybook-addon-next/examples/node_modules/storybook-addon-next/dist/preset.js:29:35
ERR!     at Generator.next (<anonymous>)
ERR!     at fulfilled (<project-root>/storybook-addon-next/examples/node_modules/tslib/tslib.js:114:62)
ERR!  Error: Cannot find module '<project-root>/storybook-addon-next/examples/with-tailwindcss/node_modules/next/package.json'
ERR! Require stack:
ERR! - <project-root>/storybook-addon-next/examples/node_modules/storybook-addon-next/dist/utils.js
ERR! - <project-root>/storybook-addon-next/examples/node_modules/storybook-addon-next/dist/preset.js
ERR! - <project-root>/storybook-addon-next/examples/node_modules/@storybook/core-common/dist/cjs/presets.js
ERR! - <project-root>/storybook-addon-next/examples/node_modules/@storybook/core-common/dist/cjs/index.js
ERR! - <project-root>/storybook-addon-next/examples/node_modules/@storybook/core-server/dist/cjs/index.js
ERR! - <project-root>/storybook-addon-next/examples/node_modules/@storybook/core/dist/cjs/server.js
ERR! - <project-root>/storybook-addon-next/examples/node_modules/@storybook/core/server.js
ERR! - <project-root>/storybook-addon-next/examples/node_modules/@storybook/react/dist/cjs/server/index.js
ERR! - <project-root>/storybook-addon-next/examples/node_modules/@storybook/react/bin/index.js
ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!     at getNextjsVersion (<project-root>/storybook-addon-next/examples/node_modules/storybook-addon-next/dist/utils.js:9:1)
ERR!     at configureStaticImageImport (<project-root>/storybook-addon-next/examples/node_modules/storybook-addon-next/dist/images/webpack.js:14:50)
ERR!     at configureImages (<project-root>/storybook-addon-next/examples/node_modules/storybook-addon-next/dist/images/webpack.js:8:5)
ERR!     at <project-root>/storybook-addon-next/examples/node_modules/storybook-addon-next/dist/preset.js:29:35
ERR!     at Generator.next (<anonymous>)
ERR!     at fulfilled (<project-root>/storybook-addon-next/examples/node_modules/tslib/tslib.js:114:62) {
ERR!   code: 'MODULE_NOT_FOUND',
ERR!   requireStack: [
ERR!     '<project-root>/storybook-addon-next/examples/node_modules/storybook-addon-next/dist/utils.js',
ERR!     '<project-root>/storybook-addon-next/examples/node_modules/storybook-addon-next/dist/preset.js',
ERR!     '<project-root>/storybook-addon-next/examples/node_modules/@storybook/core-common/dist/cjs/presets.js',
ERR!     '<project-root>/storybook-addon-next/examples/node_modules/@storybook/core-common/dist/cjs/index.js',
ERR!     '<project-root>/storybook-addon-next/examples/node_modules/@storybook/core-server/dist/cjs/index.js',
ERR!     '<project-root>/storybook-addon-next/examples/node_modules/@storybook/core/dist/cjs/server.js',
ERR!     '<project-root>/storybook-addon-next/examples/node_modules/@storybook/core/server.js',
ERR!     '<project-root>/storybook-addon-next/examples/node_modules/@storybook/react/dist/cjs/server/index.js',
ERR!     '<project-root>/storybook-addon-next/examples/node_modules/@storybook/react/bin/index.js'
ERR!   ]
ERR! }

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Your minimal, reproducible example

https://github.com/volkyeth/storybook-addon-next/tree/broken-with-yarn-workspaces

### Steps to reproduce

```
git clone --branch broken-with-yarn-workspaces git@github.com:volkyeth/storybook-addon-next.git
cd storybook-addon-next/examples
yarn install
cd with-tailwindcss
yarn storybook
```

### Expected behavior

Package should work with yarn workspaces

### How often does this bug happen?

Every time

### Platform

OS: MacOS

### storybook-addon-next version

1.4.2

### Additional context

I'm not sure what's the fix for this as I'm not very experienced at packaging libs. I'll try to look into it but if someone knows how to make it compatible please advise and I'll try to make a PR

**Comment by volkyeth** [comment]
btw, the workaround for this is using the [nohoist](https://classic.yarnpkg.com/blog/2018/02/15/nohoist/) option on the root package.json like so:
```
{
    "private": true,
    "workspaces": {
        "packages": [
            "with-tailwindcss"
        ],
        "nohoist": [
            "**/storybook-addon-next",
            "**/storybook-addon-next/**"
        ]
    }
}
```

this way the `node_modules` with dependencies of `storybook-addon-next` is kept on the folder of the package using it, so it can find the dependencies

**Comment by RyanClementsHax** [comment]
Thanks for opening up this issue!

[Here](https://github.com/RyanClementsHax/storybook-addon-next/issues/22#issuecomment-1034926047) you mentioned that storybook dependencies don't work well for yarn workspaces either. Could you clarify? Also if that is the case, is this problem worth fixing in this repo if storybook can't be used with it?

**Comment by RyanClementsHax** [comment]
Yeah, I'd agree. How are package resolutions supposed to work in mono repos like that?

**Comment by 0xsven** [comment]
Imagine the following folder structure:
```
/packages
  /my-storybook
    /.storybook
    /stories
    /package.json
  /ui-library
    /Button.jsx
    /package.json
/node_modules
/package.json
/package-lock.json
```

If you run `npm install` npm/yarn will go through your packages' `package.json` file and install all their dependencies withing the root's `/node_modules` folder and link them together. So there only is one `node_modules` folder and one `package-lock.json` file.

In this example the workspace "my-storybook" imports the `ui-library` workspace and displays it within storybook.

This setup is very usefull for bigger projects, as you can exclude certain packages (and their dependencies) when deploying and so speed up your pipelines. Also it makes your project nicely structured and understandable...

**Comment by volkyeth** [comment]
@RyanClementsHax what makes packages incompatible with workspaces is missing some dependency declarations or explicitly referencing the `node_modules` folder, as yarn workspaces hoists the subprojects `node_modules` folders up to the monorepo folder, and the newer yarn pnp does not even have a `node_modules`, so any dependency on the regular folder structure breaks the packages.

[over here](https://github.com/RyanClementsHax/storybook-addon-next/blob/418050899544fa82cdf234810b6154db4e945e6d/src/utils.ts#L8) I think using [`require.resolve`](https://dev.to/stephencweiss/what-is-require-resolve-and-how-does-it-work-1ho4) fixes the issue

I'm not sure how to solve it in [.czrc](https://github.com/RyanClementsHax/storybook-addon-next/blob/56337307530cbb662668e909d7d8828f6d0d5d30/.czrc) and [.husky](https://github.com/RyanClementsHax/storybook-addon-next/blob/56337307530cbb662668e909d7d8828f6d0d5d30/.husky/prepare-commit-msg) though

**Comment by volkyeth** [comment]
Fixed in #26

**Comment by 0xsven** [comment]
The previous errors are gone! 🥳
There are some new ones (see error below).

I am trying to get the basic example from [next/examples](https://github.com/vercel/next.js/tree/canary/examples/with-storybook) running within my project.

```
npm run storybook

> webapp@1.5.2 storybook
> turbo run storybook

• Packages in scope: config, e2e, generated, storybook, tsconfig, ui, web
• Running storybook in 7 packages
storybook: cache miss, executing 7e6fa4dd60a59a63
storybook:
storybook: > storybook
storybook: > start-storybook -p 6006
storybook:
storybook: info @storybook/react v6.4.19
storybook: info
storybook: info => Loading presets
storybook: info => Using implicit CSS loaders
storybook: info => Using default Webpack5 setup
storybook: <s> [webpack.Progress] 0%
storybook:
storybook: <s> [webpack.Progress] 1% setup initialize
storybook: [...]
storybook: <s> [webpack.Progress] 100%
storybook:
storybook: ModuleBuildError: Module build failed (from ../../node_modules/css-loader/dist/cjs.js):
storybook: ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
storybook:  - options.url should be one of these:
storybook:    boolean | object { filter? }
storybook:    -> Allows to enables/disables `url()`/`image-set()` functions handling.
storybook:    -> Read more at https://github.com/webpack-contrib/css-loader#url
storybook:    Details:
storybook:     * options.url should be a boolean.
storybook:     * options.url should be an object:
storybook:       object { filter? }
storybook:  - options.import should be one of these:
storybook:    boolean | object { filter? }
storybook:    -> Allows to enables/disables `@import` at-rules handling.
storybook:    -> Read more at https://github.com/webpack-contrib/css-loader#import
storybook:    Details:
storybook:     * options.import should be a boolean.
storybook:     * options.import should be an object:
storybook:       object { filter? }
storybook:     at validate (/code/webapp/node_modules/schema-utils/dist/validate.js:105:11)
storybook:     at Object.getOptions (/code/webapp/node_modules/webpack/lib/NormalModule.js:580:19)
storybook:     at Object.loader (/code/webapp/node_modules/css-loader/dist/index.js:31:27)
storybook:     at processResult (/code/webapp/node_modules/webpack/lib/NormalModule.js:753:19)
storybook:     at /code/webapp/node_modules/webpack/lib/NormalModule.js:855:5
storybook:     at /code/webapp/node_modules/loader-runner/lib/LoaderRunner.js:399:11
storybook:     at /code/webapp/node_modules/loader-runner/lib/LoaderRunner.js:251:18
storybook: ModuleBuildError: Module build failed (from ../../node_modules/css-loader/dist/cjs.js):
storybook: ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
storybook:  - options.url should be one of these:
storybook:    boolean | object { filter? }
storybook:    -> Allows to enables/disables `url()`/`image-set()` functions handling.
storybook:    -> Read more at https://github.com/webpack-contrib/css-loader#url
storybook:    Details:
storybook:     * options.url should be a boolean.
storybook:     * options.url should be an object:
storybook:       object { filter? }
storybook:  - options.import should be one of these:
storybook:    boolean | object { filter? }
storybook:    -> Allows to enables/disables `@import` at-rules handling.
storybook:    -> Read more at https://github.com/webpack-contrib/css-loader#import
storybook:    Details:
storybook:     * options.import should be a boolean.
storybook:     * options.import should be an object:
storybook:       object { filter? }
storybook:     at validate (/code/webapp/node_modules/schema-utils/dist/validate.js:105:11)
storybook:     at Object.getOptions (/code/webapp/node_modules/webpack/lib/NormalModule.js:580:19)
storybook:     at Object.loader (/code/webapp/node_modules/css-loader/dist/index.js:31:27)
storybook:     at processResult (/code/webapp/node_modules/webpack/lib/NormalModule.js:753:19)
storybook:     at /code/webapp/node_modules/webpack/lib/NormalModule.js:855:5
storybook:     at /code/webapp/node_modules/loader-runner/lib/LoaderRunner.js:399:11
storybook:     at /code/webapp/node_modules/loader-runner/lib/LoaderRunner.js:251:18
storybook:
storybook:
storybook: WARN Broken build, fix the error above.
storybook: WARN You may need to refresh the browser.
storybook: Error: command finished with error: exit status 1
```

It seems like css-loader is initialized with the wrong config? 

Here are the versions of css-loader that are installed:

```
npm ls css-loader

webapp@1.5.2
└─┬ storybook@ -> ./apps/storybook
  ├─┬ @storybook/addon-essentials@6.4.19
  │ └─┬ @storybook/addon-docs@6.4.19
  │   └─┬ @storybook/builder-webpack4@6.4.19
  │     └── css-loader@3.6.0
  ├─┬ @storybook/builder-webpack5@6.4.19
  │ └── css-loader@5.2.7
  ├─┬ @storybook/manager-webpack5@6.4.19
  │ └── css-loader@5.2.7
  ├─┬ @storybook/react@6.4.19
  │ └─┬ @storybook/core@6.4.19
  │   └─┬ @storybook/core-server@6.4.19
  │     └─┬ @storybook/manager-webpack4@6.4.19
  │       └── css-loader@3.6.0
  └─┬ storybook-addon-next@1.4.3
    └── css-loader@6.6.0
```

**Comment by volkyeth** [comment]
> CSS Loader has been initialized using an options object that does not match the API schema.

This is #22 
Are you using `nohoist` on your workspace? This issue only manifested for me with nohoist because then storybook-addon-next managed to pick its own `css-loader` version and broke because of selecting the wrong one

**Comment by 0xsven** [comment]
@volkyeth 
I am not using `nohoist`. All my dependencies are hoisted to the root folder. 

From issue #22 it sounds like css-loader >6.0.0 is the issue. [storybook-addon-next](https://github.com/RyanClementsHax/storybook-addon-next) is still depending on it.

I downgraded to css-loader@5.2.7 and it works now! Thanks for the tips.

**Comment by RyanClementsHax** [comment]
@volkyeth so it turns out that the fix made in #26 breaks local development (`yarn watch`) because `require.resolve('styled-jsx')` tries to resolve to the root node modules folder instead of the examples one. Do you know of a way to preserve support for monorepos while also allowing for local development?

**Comment by volkyeth** [comment]
@RyanClementsHax yeah, that's an issue with Yarn v1 link. It's solved on Yarn v2+
Refs:
https://twitter.com/arcanis/status/1133706355888590849?s=20&t=be7t-pmMkf9EuKzd11kUPw
https://yarnpkg.com/features/protocols#whats-the-difference-between-link-and-portal

I'm trying to upgrade it so we switch from `link:` to `portal:` protocol on the examples, then I'll send a PR. Would that work for you?

In my experience, it's worth using Yarn v2+. I've been hitting so many issues with yarn that won't be fixed in v1, so I guess it's time to move on. Performance of yarn install on v2+ is also great.

**Comment by RyanClementsHax** [comment]
Interesting that it solved those problems for you. I've had a terrible time trying to get yarn link to work in v2+. I'd be happy to see what u come up with.

I do have one concern with yarn v2+ that I was hoping you could help answer. Why does it seem no one uses yarn v2+? It seems like everyone still uses v1.

**Comment by illarionvk** [comment]
> I do have one concern with yarn v2+ that I was hoping you could help answer. Why does it seem no one uses yarn v2+? It seems like everyone still uses v1.

Yarn v2 adds a runtime dependency to make the [PnP magic mode](https://yarnpkg.com/features/pnp#fixing-node_modules) work, essentially hiding the node_module folder from the tools that analyze the code statically.

In other words, the development tooling has to support Yarn PnP to work correctly.

We switched to [pnpm](https://pnpm.io/motivation) because it produces the node_modules folder with the efficiency of Yarn v2 using a unix-standard symlink/copy strategy, and it's even faster than Yarn.

For example, it takes Yarn v1 over 3 minutes to do a clean install for one of my projects with Storybook. It takes just 40 seconds with pnpm.

**Comment by RyanClementsHax** [comment]
I was able to find a way to get package resolution working with #31. That being done, I'm still interested in any ideas to improve package management within this repo.

Also ty @illarionvk for the explanation.

**Comment by RyanClementsHax** [comment]
@daviddelusenet I created a pull request (#40) that adds this feature. I'm just looking for an example repo to make sure I solved it properly. Are you able to provide one?

**Comment by thijsdaniels** [comment]
Hi @RyanClementsHax! Awesome plugin! I've checked in with @daviddelusenet offline and I can setup a quick example repo (using NPM workspaces; I've never used yarn workspaces, though I imagine the setup is very similar) early next week :) Or if you prefer, I can also test it myself next week.

**Comment by RyanClementsHax** [comment]
@thijsdaniels Thanks! I really appreciate the complements!

Someone helped out a bunch by contributing an example that uses nx (#41) which allowed me to publish a version of this repo that allows a developer to specify a path for the next config (see [options](https://github.com/RyanClementsHax/storybook-addon-next/pull/41)).

Hopefully this works for you. Let me know if it doesn't.

That being said, I'd still be open to receive any examples you're willing to contribute.

**Comment by thijsdaniels** [comment]
@RyanClementsHax Sorry for disappearing for a while! Just tested with our NPM workspaces setup and it works like a charm :)

**Comment by RyanClementsHax** [comment]
No problem! It happens. I'm glad it worked out for you
