### ISSUE TITLE
Thank you! ❤️ 

### ISSUE THREAD

**Issue by leerob** [RyanClementsHax/storybook-addon-next#3]
Just wanted to say thank you for creating this - it's awesome!

**Comment by leerob** [comment]
Thoughts on merging one of your examples here back to `with-storybook`? 

https://github.com/vercel/next.js/tree/canary/examples/with-storybook

**Comment by RyanClementsHax** [comment]
Thanks so much! That means a lot!

I'd be happy to merge in an example! Just to be clear, you want me to merge this in with the existing "with-storybook" example? Also would you like me to basically merge in my nextv12 example? It demos everything this supports but it isn't very pretty for sake of simplicity.

As a side note, how did you find out about this addon? I'm still amazed at how fast word spreads in open source.

**Comment by leerob** [comment]
Yeah, I'd say moving https://github.com/RyanClementsHax/storybook-addon-next/tree/main/examples/nextv12 to `with-storybook` in the Next.js examples folder. I can review the PR! I found it through Storybook talking about it 😄
