### ISSUE TITLE
Currently not working when using src directory

### ISSUE THREAD

**Issue by scpaye506** [RyanClementsHax/storybook-addon-next#46]
### Describe the bug

Currently does not work when using the the src directory feature - https://nextjs.org/docs/advanced-features/src-directory.

### Your minimal, reproducible example

https://github.com/scpaye506/nextjs-storybook-addon-src-bug

### Steps to reproduce

1. pull down repo
2. `npm install`
3. `npm run storybook`

### Expected behavior

As a user, I expected storybook to run when using a src directory, but got the below errors:

```
ModuleNotFoundError: Module not found: Error: Can't resolve '../styles/globals.css'
```

### How often does this bug happen?

Every time

### Platform

- OS: Mac

### storybook-addon-next version

v1.4.4

**Comment by RyanClementsHax** [comment]
Thanks for reporting this issue!

As it turns out, this addon does support the `src` directory feature. The problem was actually caused by bad import paths in the application code.

```diff
module.exports = {
-  stories: [
-    '../stories/**/*.stories.mdx',
-    '../stories/**/*.stories.@(js|jsx|ts|tsx)',
-  ],
+  stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    'storybook-addon-next',
  ],
  core: {
    builder: 'webpack5',
  },
}
```
```diff
-import '../styles/globals.css'
+import '../src/styles/globals.css'

export const parameters = {
  actions: { argTypesRegex: '^on[A-Z].*' },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
}
```
