### ISSUE TITLE
Doesn't work when using Next.js's Runtime Configuration

### ISSUE THREAD

**Issue by Vinnl** [RyanClementsHax/storybook-addon-next#47]
### Describe the bug

When a component that's in a story calls a function that calls [`getConfig`](https://nextjs.org/docs/api-reference/next.config.js/runtime-configuration), Storybook will error:

```
next_config__WEBPACK_IMPORTED_MODULE_0__["default"]() is undefined

loadConfig@http://localhost:6006/main.iframe.bundle.js:206:65
```

![image](https://user-images.githubusercontent.com/4251/156024205-6497f888-6ea2-4520-a8a0-d47e016a87d8.png)

### Your minimal, reproducible example

git@github.com:Vinnl/repro-storybook-addon-next-getconfig.git

### Steps to reproduce

1. `git clone git@github.com:Vinnl/repro-storybook-addon-next-getconfig.git`
2. `npm install`
3. `npm run storybook`
4. Open the IndexPage story.

### Expected behavior

A story with the page is opened, showing 

```json
{
    someKey: "some value",
  }
```

Instead, you see the error described above.

### How often does this bug happen?

Every time

### Platform

- Fedora Linux 35
- Firefox 97

### storybook-addon-next version

1.5.0

**Comment by RyanClementsHax** [comment]
Support for this has been released in version 1.6.0.

Let me know if this doesn't work out for you

**Comment by Vinnl** [comment]
That was an amazing turnaround time, thank you so much. It works like a charm. And also thanks a lot for the addon in the first place!

**Comment by RyanClementsHax** [comment]
Thanks a bunch :) that means a lot
