### ISSUE TITLE
Cannot find module {MY-FOLDER-NAME-CUT}

### ISSUE THREAD

**Issue by FrancoRATOVOSON** [RyanClementsHax/storybook-addon-next#53]
### Describe the bug

I don't know why I'm facing the same error when I start storybook.

I tried 3 times with 3 different projects and my folder name is just cut off.

### Your minimal, reproducible example

https://github.com/FrancoRATOVOSON/coeur-next

### Steps to reproduce

1. Install storybook-addon-next: yarn add storybook-addon-next -D
2. Add 'storybook-addon-next' to main.js file
3. Lanch storybook: yarn storybook

![issue_1](https://user-images.githubusercontent.com/56756707/157877839-c3374ac4-e2a1-49b5-87c8-b8cb7c2288c5.png)

Saw the same problem 2 times :

![issue_2](https://user-images.githubusercontent.com/56756707/157878005-8b93e661-9030-45c9-b59b-3cc32b4e0e44.png)

Here's my package.json

```
"dependencies": {
    "next": "12.1.0",
    "react": "17.0.2",
    "react-dom": "17.0.2"
  },
  "devDependencies": {
    "@babel/core": "^7.17.5",
    "@storybook/addon-actions": "^6.4.19",
    "@storybook/addon-essentials": "^6.4.19",
    "@storybook/addon-interactions": "^6.4.19",
    "@storybook/addon-links": "^6.4.19",
    "@storybook/builder-webpack5": "^6.4.19",
    "@storybook/manager-webpack5": "^6.4.19",
    "@storybook/react": "^6.4.19",
    "@storybook/testing-library": "^0.0.9",
    "@types/node": "17.0.21",
    "@types/react": "17.0.39",
    "babel-loader": "^8.2.3",
    "eslint": "8.10.0",
    "eslint-config-next": "12.1.0",
    "eslint-plugin-storybook": "^0.5.7",
    "storybook-addon-next": "^1.6.1",
    "typescript": "4.6.2"
  }
```

And my main.js

```
module.exports = {
  "stories": [
    "../stories/**/*.stories.mdx",
    "../stories/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions",
    "storybook-addon-next"
  ],
  "framework": "@storybook/react",
  "core": {
    "builder": "webpack5"
  }
}
````

It's an empty project I created to test the behavior and got the same issue.

### Platform

- OS : Windows 10

### storybook-addon-next version

^1.6.1

**Comment by RyanClementsHax** [comment]
Thanks for opening an issue!

It turns out that I wasn't handling windows file paths properly. I'm deploying a fix now. Let me know if the updated version works for you.

**Comment by FrancoRATOVOSON** [comment]
Thank you, it worked well for me.
