### ISSUE TITLE
Image experimental layout="raw" support

### ISSUE THREAD

**Issue by rolandtoth** [RyanClementsHax/storybook-addon-next#70]
### Describe the bug

I'm using the experimental "raw" layout but with storybook I get the following error:

> The "raw" layout is currently experimental and may be subject to breaking changes. To use layout="raw", include `experimental: { images: { layoutRaw: true } }` in your next.config.js file.

![image](https://user-images.githubusercontent.com/5349356/162533161-5e36ea5c-2f1b-46cd-b150-cfbc5bb76020.png)

I do have allowed this experimental feature in next.config.js, and also configured storybook main.js to use the next.config.js file ("nextConfigPath"). However it doesn't seem to work.

Are experimental features not supported, or is there anything I could do to make this work?

### Your minimal, reproducible example

not yet...

### Steps to reproduce

Create a storybook with an Image component with props `layout="raw"`.

### Expected behavior

If the experimental `images: { layoutRaw: true, }` is available in next.config.js, the Image component should load.

### Platform

Ubuntu 20.04 (WSL2)
Next.js 12.1.4
Storybook 6.4.19
storybook-addon-next 1.6.2

### storybook-addon-next version

1.6.2

**Comment by rolandtoth** [comment]
I could get rid of the error with the workaround here:
https://stackoverflow.com/questions/64622746/how-to-mock-next-js-image-component-in-storybook

It was crucial to find a way to fix this because we are also using Storyshots, and our unit tests also failed, not only Storybook.

If experimental features support is not supported than please close this issue.

**Comment by RyanClementsHax** [comment]
Thanks for opening the issue! This is actually a bug. I didn’t think of this use case and don’t load the image config like nextjs does. I'll get to work on this soon. I'm glad at least you were able to find a work around. 

By any chance, are you able to post the specific code you ended up using so other people stumbling on this issue can find it?

**Comment by RyanClementsHax** [comment]
Update: the way nextjs resolves default values in its config, which is needed to properly pass image config into the image component, is complicated and changes a lot between versions. Nextjs also doesn't export a function that can do this for us well. This will take some time to develop a clean solution. For now, please see the stackoverflow link referenced above.

**Comment by rolandtoth** [comment]
I see, thanks for the info.

**Comment by supposedlysam-bb** [comment]
First of all, thank you for all your hard work on this! I'm coming to this from #67. I would also like the ability to use the built in cloudinary loader. Thanks!

**Comment by rolandtoth** [comment]
(FYI) I tried the latest 12.1.5 Next.js and the workaround I linked above does not work anymore.

**Comment by supposedlysam-bb** [comment]
> (FYI) I tried the latest 12.1.5 Next.js and the workaround I linked above does not work anymore.

FWIF, I was able to get the workaround working with 12.1.5.

I first needed to use the `npx sb@next upgrade --prerelease` command to upgrade my Storybook from webpack 4 to webpack 5. Then I was able to add the following to my `.storybook.main.js` file

```js
const path = require("path");
const webpack = require("webpack");

module.exports = {
  stories: [
    "../stories/**/*.stories.mdx",
    "../stories/**/*.stories.@(js|jsx|ts|tsx)",
  ],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-a11y",
    {
      name: "@storybook/addon-postcss",
      options: {
        postcssLoaderOptions: {
          implementation: require("postcss"),
        },
      },
    },
  ],
  webpackFinal: async (config, { configType }) => {
    // Mocking out next/config until the storybook addon next fixes a bug to pull in image loaders
    // Source: https://stackoverflow.com/questions/64622746/how-to-mock-next-js-image-component-in-storybook
    // Related issues:
    //   - https://github.com/RyanClementsHax/storybook-addon-next/issues/67
    //   - https://github.com/RyanClementsHax/storybook-addon-next/issues/70

    const nextConfigPath = path.resolve(__dirname, "../next.config.js");
    const nextConfig = require(nextConfigPath);

    config.plugins.push(
      new webpack.DefinePlugin({
        "process.env.__NEXT_IMAGE_OPTS": JSON.stringify({
          deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
          imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
          domains: [],
          ...nextConfig.images,
        }),
      })
    ); // Return the altered config

    return config;
  },
  core: {
    builder: "webpack5", // This gets added when running sb@next upgrade
  },
};
```

We already had the correct code in the `preview.js` like they describe in the link so I didn't need to update that.

**Comment by RyanClementsHax** [comment]
After looking into this further, I have a working solution on the [image-config](https://github.com/RyanClementsHax/storybook-addon-next/tree/image-config) branch.

The problem I'm working through now is how I'm going to deal with how the addon already [unoptimizes](https://github.com/RyanClementsHax/storybook-addon-next#optimization) images (that was the poor man's way of getting next/image working in storybook). Injecting image config seems to be a more robust and "correct" way of dealing with images.

It seems to me like I should remove the automatic unoptimization and publish this as v2.

I'll have to do more research into this, but because of these new findings, this is actually intended behavior so I'll remove the bug label.

**Comment by RyanClementsHax** [comment]
Go away

**Comment by RyanClementsHax** [comment]
I have created this discussion to centralize supporting these nextjs props https://github.com/RyanClementsHax/storybook-addon-next/discussions/119
