### ISSUE TITLE
Dont resolve paths from tsconfig

### ISSUE THREAD

**Issue by StephanAksenchenko** [RyanClementsHax/storybook-addon-next#71]
### Describe the bug

Nextjs automatically support tsconfig's paths and base url while addon add only root path to module resolution.

`export const configureAbsoluteImports = (baseConfig: WebpackConfig): void =>
  void baseConfig.resolve?.modules?.push(path.resolve())` [here](https://github.com/RyanClementsHax/storybook-addon-next/blob/main/src/absoluteImports/webpack.ts)

### Your minimal, reproducible example

https://github.com/StephanAksenchenko/Sb-addon-next-bug

### Steps to reproduce

1. use node 16.14.0
2. yarn
3. yarn dev       // run development server and it works right
4. yarn storybook        //  get exception about module resolution

### Expected behavior

I expect it should work identically

### How often does this bug happen?

Every time

### Platform

Os - linux
Node - 16.14.0

### storybook-addon-next version

v 1.6.2

**Comment by rosman83** [comment]
Experiencing this same issue

**Comment by RyanClementsHax** [comment]
Oh thanks for pointing this out! I appreciate the time you took to fill out an issue. Do you have a good workaround available that you could share?

For anyone stumbling on this issue. I believe using tsconfig-paths-webpack-plugin and configuring it as shown in the issue link below should be the preferred workaround.

I'll get this integrated into this package soon. (My wife and kid are both sick right now so I've been taking care of them lately. They should be better soon though.) Thanks for your patience.

https://www.npmjs.com/package/tsconfig-paths-webpack-plugin

https://github.com/storybookjs/storybook/issues/3291#issuecomment-984568831
