### ISSUE TITLE
CSS import not working in .storybook/preview.js after adding 'storybook-addon-next',

### ISSUE THREAD

**Issue by AmandeepTelus** [RyanClementsHax/storybook-addon-next#74]
### Describe the bug

Hi I am using Storybook 6.4.22 with Next 12.1.5 and Typescript 4.4.2(Node 16). I have to add global fonts for our stories. I tried adding that in preview.js and it worked fine initially. I had to use 'storybook-addon-next' because some of our components are pulling info out of configs(getConfig()?.serverRuntimeConfig?.config). After adding the addon my global import of fonts has stopped working.
Thanks in advance for your help.

## storybook/Main.js
```
module.exports = {
stories: ['../src//*.stories.mdx', '../src//*.stories.@(js|jsx|ts|tsx)'],
addons: [
'@storybook/addon-links',
'@storybook/addon-essentials',
'@storybook/addon-interactions',
'storybook-addon-tags',
'storybook-addon-next',
],
framework: '@storybook/react',
core: {
builder: '@storybook/builder-webpack5',
},
}
```
## storybook/preview.js
```
import '@UI/palette/build/web/fonts/fonts-cdn.css' //css import
export const parameters = {
actions: { argTypesRegex: '^on[A-Z].*' },
controls: {
matchers: {
color: /(background|color)$/i,
date: /Date$/,
},
},
}
```

### Your minimal, reproducible example

explained above

### Steps to reproduce

explained above

### Expected behavior

none

### Screenshots or Videos

none

### Platform

-OS[MAC OS]

### storybook-addon-next version

"^1.6.2"

**Comment by RyanClementsHax** [comment]
Thanks for opening up an issue! I'd be happy to look into this.

Can you provide a minimal reproduction repo that I can dig into? Basic repo steps are ok, but I want to make sure that I'm actually solving your issue. I also have only a limited amount of time to work on this per day so I want to make sure that time is used as best as possible to solve your problem. It would be a shame If I waste hours that a fix for you could have been deployed trying to get something set up that ~might~ be your issue.

Thanks for your help

**Comment by AmandeepTelus** [comment]
Hey @RyanClementsHax , my apologies for a late reply. thanks for looking into this so quickly. I have added the steps to reproduce please have a look and let me know if you need any more details.
Thanks a ton.

**Comment by RyanClementsHax** [comment]
@AmandeepTelus I see you closed this? Is this no longer an issue for you?

**Comment by AmandeepTelus** [comment]
Hey Ryan Yeah, So i had to add a new css file in the preview.js and in that file i added my import statement  `@import '@telus-uds/palette-allium/build/web/fonts/fonts-cdn.css'` and this worked

**Comment by RyanClementsHax** [comment]
I'm glad it worked out for you! :) Lmk if you run into any further problems.

**Comment by AmandeepTelus** [comment]
Will do thanks , have a good night

**Comment by pfcodes** [comment]
I'm having this issue. What's weird is that after installing `storybook-addon-next` relative imports in `preview.js` stop working while absolute imports still work:

```
import 'swiper/css'
import 'swiper/css/navigation'
import 'swiper/css/pagination'
import 'photoswipe/dist/default-skin/default-skin.css'
import 'photoswipe/dist/photoswipe.css'
import '../src/assets/global.css' <- doesn't work
import '../src/features/help-center/assets/help-center.css' <-- doesn't work
```

**Comment by RyanClementsHax** [comment]
Could you please provide a minimal reproduction repo?
