### ISSUE TITLE
Image domain warning >= Next.js v12.1.5

### ISSUE THREAD

**Issue by ThomasVanleynseele** [RyanClementsHax/storybook-addon-next#78]
### Describe the bug

Receiving the following error message: `Invalid src prop (http://loremflickr.com/640/480/transport) on `next/image`, hostname "loremflickr.com" is not configured under images in your `next.config.js``

Issue happens with Next.js >= v12.1.5 https://github.com/vercel/next.js/releases/tag/v12.1.5

### Your minimal, reproducible example

-

### Steps to reproduce

1. Use Storybook and Next.js >= v12.1.5
2. Use an image from an external domain in your Image Component
3. Error

### Expected behavior

Remote Images from an external domain should work as they did before Next.js v12.1.5 

### How often does this bug happen?

Every time

### Platform

- Platform: Mac

### storybook-addon-next version

v1.6.2

**Comment by FernandoGOT** [comment]
Hi, I just got the same problem, it's as if the storybook didn't load the next.config.js, did you find a fix for it?

**Comment by RyanClementsHax** [comment]
I think #72 might be related to this
