### ISSUE TITLE
WebpackOptionsValidationError when starting

### ISSUE THREAD

**Issue by tremby** [RyanClementsHax/storybook-addon-next#79]
### Describe the bug

After adding this addon to a fresh NextJS and Storybook and storybook-addon-next installation all with default configuration, and attempting to start Storybook, I have an error.

### Your minimal, reproducible example

Run commands below

### Steps to reproduce

1. `npx create-next-app@latest bug`
2. `cd bug`
3. `npx sb init`, say yes or no to eslintPlugin question, doesn't make a difference
4. `npm i -D --force storybook-addon-next` (force needed because otherwise peer dependency fails; see #68 which isn't yet released)
5. Edit `.storybook/main.js`, add 'storybook-addon-next` to the end (or start, no difference) of the `addons` array
6. `npm run storybook`
7. See error:

```
info @storybook/react v6.4.22
info
info => Loading presets
info => Using implicit CSS loaders
info => Using default Webpack4 setup
ERR! WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
ERR!  - configuration.module.rules[12].type should be one of these:
ERR!    "javascript/auto" | "javascript/dynamic" | "javascript/esm" | "json" | "webassembly/experimental"
ERR!    -> Module type to use for the module
ERR!     at webpack (/path/to/bug/node_modules/webpack/lib/webpack.js:31:9)
ERR!     at Object.start (/path/to/bug/node_modules/@storybook/builder-webpack4/dist/cjs/index.js:92:18)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (/path/to/bug/node_modules/@storybook/core-server/dist/cjs/dev-server.js:126:28)
ERR!     at async buildDevStandalone (/path/to/bug/node_modules/@storybook/core-server/dist/cjs/build-dev.js:115:31)
ERR!     at async buildDev (/path/to/bug/node_modules/@storybook/core-server/dist/cjs/build-dev.js:161:5)
ERR!  WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
ERR!  - configuration.module.rules[12].type should be one of these:
ERR!    "javascript/auto" | "javascript/dynamic" | "javascript/esm" | "json" | "webassembly/experimental"
ERR!    -> Module type to use for the module
ERR!     at webpack (/path/to/bug/node_modules/webpack/lib/webpack.js:31:9)
ERR!     at Object.start (/path/to/bug/node_modules/@storybook/builder-webpack4/dist/cjs/index.js:92:18)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (/path/to/bug/node_modules/@storybook/core-server/dist/cjs/dev-server.js:126:28)
ERR!     at async buildDevStandalone (/path/to/bug/node_modules/@storybook/core-server/dist/cjs/build-dev.js:115:31)
ERR!     at async buildDev (/path/to/bug/node_modules/@storybook/core-server/dist/cjs/build-dev.js:161:5)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

### Expected behavior

Storybook starts

### How often does this bug happen?

Every time

### Platform

- OS: Linux
- Browser: n/a

### storybook-addon-next version

1.6.2

### Additional context

I had to install the package with `--force`, since #68 is not yet released.

**Comment by RyanClementsHax** [comment]
Thanks for opening this!

It seems that you are using the webpack 4 builder instead of the webpack 5 builder. Can you try to use the webpack 5 builder and see if that works for you?

The instructions are [here](https://github.com/RyanClementsHax/storybook-addon-next#requirements)

**Comment by tremby** [comment]
I've no idea which builder I'm using. It's whatever is currently default for Next and Storybook -- this is in line with "no config", isn't it? ;)

Yes, the error goes away if I replace the Storybook line with `npx sb init --builder webpack5`.

Is there some way to give a friendlier error message in this situation? Perhaps you can detect Storybook was set up with Webpack 4 and emit a warning?

**Comment by tremby** [comment]
In my actual project, however, I'm getting `Error: Cannot find module 'webpack/lib/util/makeSerializable.js'`, with a stacktrace pointing to react-docgen-typescript-plugin. I've no idea if that's a bug with this package, or with Storybook, or with react-docgen-typescript-plugin.

Reproducable from scratch with

```
npx create-next-app@latest bug --typescript
cd bug
npx sb init --builder webpack5 # and say yes to linter
npm i -D --force storybook-addon-next
< add addon to config >
npm run storybook
```

**Comment by RyanClementsHax** [comment]
Oh my. That's an error storybook hasn't fixed yet (you can search for this issues on their GitHub project page). The current working solution is to install webpack as a dev dependency to your project.

I should probably put something addressing this in the docs.

Thanks for bringing this to my attention. I really appreciate it.

**Comment by tremby** [comment]
Ah while you responded here I thought "this ought to be a separate ticket" and opened #80. I'll look at storybook's issues...

**Comment by tremby** [comment]
Oh my goodness I'd missed part of what you said above:

> The current working solution is to install webpack as a dev dependency to your project.

It's working beautifully now. Thank you!

I'll leave this open since I think a better error message for when webpack 5 hasn't been activated would be a good idea.
