### ISSUE TITLE
Stoyybook Addon Next break Storybook when is used with Vite builder

### ISSUE THREAD

**Issue by RodrigoTomeES** [RyanClementsHax/storybook-addon-next#84]
### Describe the bug

When use this plugin with Vite builder Storybook always show the error `Invalid Version: undefined`

### Your minimal, reproducible example

updating

### Steps to reproduce

Install Storybook with Vite builder and this plugin

### Expected behavior

That this plugin could work with Vite builder

### Screenshots or Videos

<img width="1206" alt="imagen" src="https://user-images.githubusercontent.com/13077343/170375673-18c454cb-ecd0-458f-b8bf-c1ebea0f2f68.png">

### Platform

MacOS 12.3.1

### storybook-addon-next version

1.6.4

**Comment by RyanClementsHax** [comment]
Thanks for bringing this up.

Unfortunately this project only supports the webpack 5 builder. If there is enough community support, I'll consider adding support for the vote builder.

**Comment by Handfish** [comment]
@RodrigoTomeES 

I've put together a Vite Storybook solution for next/future/Image that works well enough for myself. It does not require this installing this addon.

`main.js`
```
module.exports = {
  stories: [...],
  addons: [
    ...
  ],
  framework: "@storybook/react",
  core: {
    builder: "@storybook/builder-vite",
  },
  async viteFinal(config, { configType }) {
    return {
      ...config,
      define: {
          'process.env.__NEXT_IMAGE_OPTS': JSON.stringify({
            experimentalFuture: true
          }),
      },
      resolve: {
         // https://github.com/RyanClementsHax/storybook-addon-next/issues/99#issuecomment-1172943217
         // Creates an extra "div" around the image - may cause some discrepancies between storybook and production
        alias: [
          {
            find: "next/image",
            replacement: "next/future/image",
          },
        ],
      },
    };
  },
};
```
  
 `preview.jsx`
 ```
import * as NextImage from "next/image";

//Tailwind or whatever
import '../index.css';


const OriginalNextImage = NextImage.default;

Object.defineProperty(NextImage, "default", {
  configurable: true,
  value: (props) => typeof props.src === 'string' ? (
    <OriginalNextImage {...props} unoptimized blurDataURL={props.src} />
  ) : (
    <OriginalNextImage {...props} unoptimized />
  ),
});
```

**Comment by RodrigoTomeES** [comment]
Hi, @RyanClementsHax now Vite will be the default builder in Storybook 7 so, I think vite builder should be supported.

**Comment by moodiest** [comment]
It would be nice to see this revisited.
