### ISSUE TITLE
storybook-addon-next does not work with tailwindcss 3.

### ISSUE THREAD

**Issue by kyujonglee** [RyanClementsHax/storybook-addon-next#85]
### Describe the bug

1. tailwindcss3 works well when using `@storybook/addon-postcss`
   (because tailwindcss3. needs postcss 8+. but storybook does not support postcss 8+.)

```javascript
const path = require('path');

module.exports = {
  stories: [
    '../stories/**/*.stories.mdx',
    '../stories/**/*.stories.@(js|jsx|ts|tsx)',
  ],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
    {
      name: '@storybook/addon-postcss',
      options: {
        postcssLoaderOptions: {
          implementation: require('postcss'),
        },
      },
    },
  ],
  framework: '@storybook/react',
  core: {
    builder: '@storybook/builder-webpack5',
  },
  webpackFinal: async (config) => {
    config.resolve.modules = [path.resolve(__dirname, '..'), 'node_modules'];

    return config;
  },
  staticDirs: ['../public'],
};

```

2. but, storybook-addon-next does not work with postcss 8+. :(. please help.

```javascript
const path = require('path');

module.exports = {
  stories: [
    '../stories/**/*.stories.mdx',
    '../stories/**/*.stories.@(js|jsx|ts|tsx)',
  ],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
    'storybook-addon-next',
    {
      name: '@storybook/addon-postcss',
      options: {
        postcssLoaderOptions: {
          implementation: require('postcss'),
        },
      },
    },
  ],
  framework: '@storybook/react',
  core: {
    builder: '@storybook/builder-webpack5',
  },
  webpackFinal: async (config) => {
    config.resolve.modules = [path.resolve(__dirname, '..'), 'node_modules'];

    return config;
  },
  staticDirs: ['../public'],
};

```

It occurs this error message.
`Error: PostCSS plugin tailwindcss requires PostCSS 8.`

### Your minimal, reproducible example

https://github.com/kyujonglee/storybook-nextjs-tailwindcss

### Steps to reproduce

1. npx create-next-app@lasest --typescript
2. npx storybook init
4. install @storybook/addon-postcss and tailwindcss postcss autoprefixer.

### Expected behavior

storybook
nextjs
tailwindcss3

work together.

### Platform

- OS: macOS
- browser: Chrome

### storybook-addon-next version

v1.6.4

**Comment by RyanClementsHax** [comment]
Oh boy do I have good news for you.

If you go to the examples portion of the readme for this addon, you will see that I have a tailwind css 3 example.

In short, you don’t need the storybook postcss addon :)

Hope this helps

**Comment by kyujonglee** [comment]
your example(`with-tailwindcss`) does not work.
please check this repo.

https://github.com/kyujonglee/storybook-nextjs-tailwindcss

**Comment by pm0u** [comment]
@RyanClementsHax where is this example? the `with-tailwindcss` example doesn't have the `@storybook/addon-postcss` plugin configured or installed that I can determine. Without or without this plugin I get the same error message as OP.

**Comment by RyanClementsHax** [comment]
Oh I'm glad everything was ok

**Comment by pm0u** [comment]
It was, and the example was helpful as well just to review the dependencies. I didn't realize that the postcss addon was no longer explicitly necessary either. Thanks again!

**Comment by RyanClementsHax** [comment]
Yup! no problem!
