### ISSUE TITLE
Object.defineProperty(NextImage, '__esModule', descriptor) is no more needed from next@12.1.7-canary.7

### ISSUE THREAD

**Issue by kazukinagata** [RyanClementsHax/storybook-addon-next#95]
### Describe the bug

Storybook will throw an error `TypeError: Cannot redefine property: __esModule` at this [line](https://github.com/RyanClementsHax/storybook-addon-next/blob/main/src/images/next-image-stub.tsx#L25) with using next@12.1.7-canary.7 or later.

### Your minimal, reproducible example

none

### Steps to reproduce

1. Use next version 12.1.7-canary.7 or later
2. run storybook
3. It gives the above error

### Expected behavior

Working Storybook

### How often does this bug happen?

Every time

### Platform

- OS: Ubuntu 18.04.5
- Browser: Chrome 102.0.5005.63
- Node: v16.14.2
- Relevant packages:
  - next: ~12.1.7-canary.7

### storybook-addon-next version

v1.6.6

### Additional context

I did some digging and found that the default import of `next/image` has been fixed by this [PR](https://github.com/vercel/next.js/pull/36877/files).

The built code looks like following, so you need not to redefine `__esModule` property on next-image-stub.tsx.

```js
if ((typeof exports.default === 'function' || (typeof exports.default === 'object' && exports.default !== null)) && typeof exports.default.__esModule === 'undefined') {
  Object.defineProperty(exports.default, '__esModule', { value: true });
  Object.assign(exports.default, exports);
  module.exports = exports.default;
}
```

### Related issues

- https://github.com/vercel/next.js/issues/36417
- https://github.com/RyanClementsHax/storybook-addon-next/issues/72

**Comment by RyanClementsHax** [comment]
Thanks for opening up this issue.

When next.js releases the next version, I'll happily update this repo or accept any PRs to make this library work with it

**Comment by Otoris** [comment]
@tubbo

Do we need to make any changes to this snippet in our storybook preview.js file?

```
// De-optimize next.js images to work with storybook
const OriginalNextImage = NextImage.default;

Object.defineProperty(NextImage, "default", {
  configurable: true,
  value: (props) => typeof props.src === 'string' ? (
    <OriginalNextImage {...props} unoptimized blurDataURL={props.src} />
  ) : (
    <OriginalNextImage {...props} unoptimized />
  ),
});

Object.defineProperty(NextImage, "__esModule", {
  configurable: true,
  value: true
});
```

**Comment by bonesoul** [comment]
upgraded to 1.6.7 already but still getting the error with storybook + chromatic combo:

```
TypeError: Cannot redefine property: __esModule
    at Function.defineProperty (<anonymous>)
    at Object../.storybook/preview.js-generated-config-entry.js (https://6220ba09a126ca003f1d9a5b-mjilyunzup.capture.chromatic.com/main.7fe25a90.iframe.bundle.js:1:2024)
    at __webpack_require__ (https://6220ba09a126ca003f1d9a5b-mjilyunzup.capture.chromatic.com/runtime~main.da7e426a.iframe.bundle.js:1:381)
    at __webpack_exec__ (https://6220ba09a126ca003f1d9a5b-mjilyunzup.capture.chromatic.com/main.7fe25a90.iframe.bundle.js:1:323746)
    at https://6220ba09a126ca003f1d9a5b-mjilyunzup.capture.chromatic.com/main.7fe25a90.iframe.bundle.js:1:325154
    at Function.__webpack_require__.O (https://6220ba09a126ca003f1d9a5b-mjilyunzup.capture.chromatic.com/runtime~main.da7e426a.iframe.bundle.js:1:987)
    at https://6220ba09a126ca003f1d9a5b-mjilyunzup.capture.chromatic.com/main.7fe25a90.iframe.bundle.js:1:325297
    at webpackJsonpCallback (https://6220ba09a126ca003f1d9a5b-mjilyunzup.capture.chromatic.com/runtime~main.da7e426a.iframe.bundle.js:1:6189)
    at https://6220ba09a126ca003f1d9a5b-mjilyunzup.capture.chromatic.com/main.7fe25a90.iframe.bundle.js:1:83
    → Failed to publish build
```

**Comment by RyanClementsHax** [comment]
@Otoris I believe that is no longer needed. The addon should do everything for you. If you come by any other issues feel free to open another issue.
